import { useMemo, useState } from 'react'
import type { Booking } from '../types'
import { bookingAddons, bookingPackage, bookingTotal, peso, phDate, todayPH } from '../types'
import { Card, EmptyState } from '../components/ui'
import { Icon, type IconName } from '../components/Icon'
import { PackageChart, RevenueChart, StatusChart } from '../components/Charts'

export function Reports({ bookings }:{bookings:Booking[]}) {
  const [start,setStart]=useState('');const [end,setEnd]=useState('');const filtered=useMemo(()=>bookings.filter(b=>(!start||b.appointment_date>=start)&&(!end||b.appointment_date<=end)),[bookings,start,end]);const active=filtered.filter(b=>b.status!=='cancelled');const paid=filtered.filter(b=>b.status==='paid');const upcoming=active.filter(b=>b.appointment_date>=todayPH());const total=paid.reduce((s,b)=>s+bookingTotal(b),0);const cancellation=filtered.length?filtered.filter(b=>b.status==='cancelled').length/filtered.length*100:0
  const metrics:Array<{label:string;value:string;detail:string;icon:IconName}>=[{label:'Paid revenue',value:peso(total),detail:'Collected only',icon:'Banknote'},{label:'Average booking value',value:peso(active.length?active.reduce((s,b)=>s+bookingTotal(b),0)/active.length:0),detail:'Active bookings',icon:'ChartNoAxesColumnIncreasing'},{label:'Upcoming expected value',value:peso(upcoming.reduce((s,b)=>s+bookingTotal(b),0)),detail:'Not necessarily collected',icon:'CalendarClock'},{label:'Cancellation rate',value:`${cancellation.toFixed(1)}%`,detail:`${filtered.filter(b=>b.status==='cancelled').length} cancelled`,icon:'Percent'}]
  const revenueMap=paid.reduce<Record<string,number>>((a,b)=>{a[b.appointment_date]=(a[b.appointment_date]||0)+bookingTotal(b);return a},{});const revenue=Object.entries(revenueMap).sort().map(([d,v])=>({label:phDate(d,{month:'short',day:'numeric'}),revenue:v}));const statuses=(['pending','confirmed','paid','cancelled'] as const).map(s=>({name:s[0].toUpperCase()+s.slice(1),value:filtered.filter(b=>b.status===s).length}));const packageData=Object.entries(active.reduce<Record<string,number>>((a,b)=>{const n=bookingPackage(b);a[n]=(a[n]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([name,count])=>({name,count}));const addons=Object.entries(active.flatMap(bookingAddons).reduce<Record<string,number>>((a,x)=>{const n=x.name||'Unnamed add-on';a[n]=(a[n]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1])
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">Reports & analytics</p><h2>Studio performance</h2><p>Revenue uses paid bookings only. Expected value is shown separately.</p></div><div className="date-range"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><span>to</span><label>Until<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></div>{filtered.length?<><div className="report-metrics">{metrics.map(m=><Card key={m.label}><span className="stat-icon"><Icon name={m.icon}/></span><div><p>{m.label}</p><strong>{m.value}</strong><span>{m.detail}</span></div></Card>)}</div><div className="dashboard-grid dashboard-grid--charts"><RevenueChart data={revenue} title="Paid revenue by appointment date"/><StatusChart data={statuses}/></div><div className="dashboard-grid dashboard-grid--lower"><PackageChart data={packageData}/><Card className="chart-card"><div className="section-heading"><div><h2>Add-on usage</h2><p>Selections across active bookings</p></div></div>{addons.length?<div className="rank-list">{addons.slice(0,7).map(([name,count],i)=><div key={name}><span>{i+1}</span><strong>{name}</strong><div><i style={{width:`${Math.max(8,count/addons[0][1]*100)}%`}}/></div><b>{count}</b></div>)}</div>:<EmptyState icon="PackageOpen" title="No add-on data" description="Add-on usage will appear once selected in bookings."/>}</Card></div></>:<Card><EmptyState icon="ChartNoAxesCombined" title="No data in this range" description="Choose a wider date range to see booking and revenue analytics."/></Card>}</div>
}
