import { useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { Review } from '../types'
import { phDate } from '../types'
import { Button, Card, EmptyState, Modal } from '../components/ui'
import { Icon } from '../components/Icon'

const name = (r:Review)=>r.reviewer_name||r.customer_name||r.name||'Anonymous'; const text=(r:Review)=>r.description||r.review||''; const visible=(r:Review)=>r.is_public??r.visible??r.is_visible??false
export function Reviews({ reviews,setReviews }:{reviews:Review[];setReviews:React.Dispatch<React.SetStateAction<Review[]>>}) {
  const [query,setQuery]=useState('');const [rating,setRating]=useState('all');const [visibility,setVisibility]=useState('all');const [deleteTarget,setDeleteTarget]=useState<Review|null>(null);const [error,setError]=useState('')
  const publicReviews=reviews.filter(visible);const average=publicReviews.length?publicReviews.reduce((s,r)=>s+Number(r.rating),0)/publicReviews.length:0
  const filtered=useMemo(()=>reviews.filter(r=>(rating==='all'||String(r.rating)===rating)&&(visibility==='all'||(visibility==='public')===visible(r))&&(!query||`${name(r)} ${text(r)}`.toLowerCase().includes(query.toLowerCase()))),[reviews,query,rating,visibility])
  const toggle=async(r:Review)=>{setError('');const field='is_public' in r?'is_public':'is_visible' in r?'is_visible':'visible';const {data,error:e}=await supabase.from('reviews').update({[field]:!visible(r)}).eq('id',r.id).select().single();if(e)setError(e.message);else setReviews(items=>items.map(x=>x.id===r.id?data as Review:x))}
  const remove=async(r:Review)=>{const {error:e}=await supabase.from('reviews').delete().eq('id',r.id);if(e)setError(e.message);else{setReviews(items=>items.filter(x=>x.id!==r.id));setDeleteTarget(null)}}
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">Customer feedback</p><h2>Review management</h2><p>Curate the testimonials shown on your customer website.</p></div></div><div className="review-summary"><Card><span className="stat-icon"><Icon name="MessageCircleMore"/></span><div><p>Public reviews</p><strong>{publicReviews.length}</strong><span>{reviews.length} total submissions</span></div></Card><Card><span className="stat-icon stat-icon--amber"><Icon name="Star"/></span><div><p>Average public rating</p><strong>{average?average.toFixed(1):'—'}</strong><span>Out of 5.0</span></div></Card></div><Card className="filter-card"><div className="search-control"><Icon name="Search" size={17}/><input placeholder="Search reviewer or review content" aria-label="Search reviews" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter by rating" value={rating} onChange={e=>setRating(e.target.value)}><option value="all">All ratings</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select><select aria-label="Filter by visibility" value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="all">All visibility</option><option value="public">Published</option><option value="hidden">Hidden</option></select></Card>{error&&<p className="form-error">{error}</p>}<div className="review-list">{filtered.length?filtered.map(r=><Card key={r.id} className="review-card"><div className="review-card__top"><div className="avatar">{name(r)[0].toUpperCase()}</div><div><strong>{name(r)}</strong><span>{phDate(r.created_at)}</span></div><span className={`visibility-badge ${visible(r)?'is-public':''}`}><Icon name={visible(r)?'Eye':'EyeOff'} size={13}/>{visible(r)?'Published':'Hidden'}</span></div><div className="stars" aria-label={`${r.rating} out of 5 stars`}>{Array.from({length:5},(_,i)=><Icon key={i} name="Star" size={16} className={i<r.rating?'filled':''}/>)}</div><p>{text(r)||'No written description was provided.'}</p><footer><Button variant="secondary" icon={visible(r)?'EyeOff':'Eye'} onClick={()=>toggle(r)}>{visible(r)?'Hide review':'Publish review'}</Button><Button variant="ghost" icon="Trash2" onClick={()=>setDeleteTarget(r)}>Delete</Button></footer></Card>):<Card><EmptyState icon="MessageSquareOff" title="No reviews found" description="Try changing your search or filters."/></Card>}</div>{deleteTarget&&<Modal title="Delete this review?" onClose={()=>setDeleteTarget(null)} footer={<><Button variant="secondary" onClick={()=>setDeleteTarget(null)}>Keep review</Button><Button variant="danger" onClick={()=>remove(deleteTarget)}>Delete permanently</Button></>}><div className="confirm-message"><span className="state-icon state-icon--danger"><Icon name="Trash2"/></span><p>The review from <strong>{name(deleteTarget)}</strong> will be permanently deleted. This action cannot be undone.</p></div></Modal>}</div>
}
